### ISSUE TITLE
Search Product : error on "polarisationChannels" function

### ISSUE THREAD

**Issue by ATroullier** [SercoSPA/CSC-Ground-Segment-Interface-Delivery-Point-Test-Suite#1]
test_map.polarisationChannels=function (element) {
    pm.expect(element.Name).eq('polarisationChannels');
    pm.expect(element.ValueType).eq('String');pm.expect(element.Value).to.be.a('string');
    pm.expect(element.Value).to.be.oneOf(["HH","VV","HV","VH"]);
};

**Test :** S1_Level-0_Std+Ann
**Request :** {{service-root-uri}}/odata/v1/Products?$expand=Attributes&$filter=(contains(Name%2C'S1_RAW__0S') and startswith(Name%2C'S1'))

Test returns : AssertionError: expected 'HH,HV' to be one of [ 'HH', 'VV', 'HV', 'VH' ]
--> 
HH,HV (HorizontalHorizontal, HorizontalVertical) is a valid Polarisation Channel for Sentinel-1 SAR images and there are even more.

https://sentinel.esa.int/web/sentinel/user-guides/sentinel-1-sar/product-overview/polarimetry

https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/acquisition-modes

Test suite & Product Attributes Mapping v1.5 both wrong

**Comment by danPen84** [comment]
Fixed in the Test Suite v1.9.1_HF
