### ISSUE TITLE
Search Product : error on "instrumentShortName" function

### ISSUE THREAD

**Issue by ATroullier** [SercoSPA/CSC-Ground-Segment-Interface-Delivery-Point-Test-Suite#2]
test_map.instrumentShortName=function (element) {
    pm.expect(element.Name).eq('instrumentShortName');
    pm.expect(element.ValueType).eq('String');
    pm.expect(element.Value).to.be.a('string');
    pm.expect(element.Value).to.be.oneOf(["MSI"]);
};

**Test :** S2_SAD_(Ancillary)
**Request :** {{service-root-uri}}/odata/v1/Products?$expand=Attributes&$top=1&$filter=(contains(Name%2C'AUX_SADATA')) and startswith(Name%2C'S2')

--> Test result : AssertionError: expected 'SAD' to be one of [ 'MSI' ]
[AD-S2-PDM-ICD\] Sentinel-2 Product Unit Definition and Metadata ICD_v1.5.zip
Excel document Sheet : "S2 SAD (Ancillary)" said instrumentShortName should be Fixed to "SAD"

Test is wrong

**Comment by danPen84** [comment]
Fixed in the Test Suite v1.9.1_HF
