### ISSUE TITLE
Search Product : error on "timeliness" function

### ISSUE THREAD

**Issue by ATroullier** [SercoSPA/CSC-Ground-Segment-Interface-Delivery-Point-Test-Suite#3]
test_map.timeliness=function (element) {
    pm.expect(element.Name).eq('timeliness');
    pm.expect(element.ValueType).eq('String');
    pm.expect(element.Value).to.be.a('string');
    pm.expect(element.Value).to.be.oneOf(["AL"]);
};

**Test :** S3_Auxiliary_Data
**Request :** {{service-root-uri}}/odata/v1/Products?$expand=Attributes&$top=1&$filter=contains(Name,'AX___MF1_AX') and startswith(Name,'S3')

Test result --> AssertionError: expected 'NR' to be one of [ 'AL' ]
&$top=1&$filter=contains(Name,'AX___MF1_AX') and startswith(Name,'S3')
will select one product which starts with S3 and contains AX___MF1_AX in its Name too

**S3__AX___MF1_AX***20210318T000000_20210318T120000_20210317T061255___________________ECW_O*_**NR**_001.SEN3.zip is a candidate

This product as timeliness **NR** as seen in this name

Please fix test suite to accept more timeliness values :

XX = 2 uppercase letters/digits indicating the applicability of the file in terms of timeliness. NR for NRT, ST for STC, NT for NTC, SN for files used on both STC & NTC, NS for files used on both NRT & STC, NN for files used on both NRT & NTC, AL for files used for NRT & STC & NTC or 2 underscores “_” if not relevant.

Or eventually update the http request to target expected products

**Comment by danPen84** [comment]
Fixed in the Test Suite v1.9.1_HF
