### ISSUE TITLE
Search product : test not applicable

### ISSUE THREAD

**Issue by ATroullier** [SercoSPA/CSC-Ground-Segment-Interface-Delivery-Point-Test-Suite#5]
Request :
{{service-root-uri}}/odata/v1/Products?$expand=Attributes&$filter=(contains(Name,'AUX_PREORB') or contains(Name,'AUX_RESORB') or contains(Name,'AUX_MOEORB') or contains(Name,'AUX_POEORB') or contains(Name,'SR___ROE_AX'))

Results :
Test Attribute processingDate for Product: S1B_OPER_AUX_RESORB_OPOD_20210311T143454_V20210311T101045_20210311T132815.EOF.zip - 30c2a9de-cb55-4c23-8d3a-5fcf232c1799
AssertionError: expected '2021-03-11T14:34:54Z' to match /\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d.\d\d\d(\d*)Z/

--> not applicable
![ProcessingDate](https://user-images.githubusercontent.com/80881293/112131735-25470c80-8bca-11eb-8c18-af3a17b3c236.png)

**Comment by danPen84** [comment]
Hello,
it seems the wrong excel (the attached is about Sentinel-3), looking at the Sentinel-1 Product Attributes Mapping_v1.5.xlsx it seems applicable:

![immagine](https://user-images.githubusercontent.com/38665161/122739245-17655e00-d283-11eb-8c8f-3b01fad33a0f.png)

**Comment by ATroullier** [comment]
You're right, sorry. Not a bug.
