### ISSUE TITLE
test returns an error on a regex that looks correct

### ISSUE THREAD

**Issue by ATroullier** [SercoSPA/CSC-Ground-Segment-Interface-Delivery-Point-Test-Suite#6]
{{service-root-uri}}/odata/v1/Subscriptions

AssertionError: expected undefined to match /\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d.\d+([+-][0-2]\d:[0-5]\d|Z)/

There is someting wrong with the regex, although the format integrates the 'Z' character :
SubmissionDate: "2021-03-22T11:32:52.504Z"

I checked the rule with https://regex101.com/
All is OK, so I don't understand why an error is returned

![regex_pb](https://user-images.githubusercontent.com/80881293/112133711-3ee95380-8bcc-11eb-82e0-abff7c3efb99.jpg)

**Comment by danPen84** [comment]
Hello,
in the Subscriptions test, there is only the "SubmissionDate" as date field.
Here it seems that in your attached "AssertionError" the "SubmissionDate" is missing/undefined in the response.

`{
    "@odata.context": "$metadata#OData.CSC.Subscription",
    "FilterParam": "Products?$filter=startswith(Name,'S1')",
    "Id": "56687f1a-da02-402b-89ec-a42938366746",
    "LastNotificationDate": null,
    "NotificationEndpoint": "http://your_value_here/your_value_here",
    "NotificationEpPassword": "your_value_here",
    "NotificationEpUsername": "your_value_here",
    "Priority": null,
    "StageOrder": false,
    "Status": "running",
    "SubmissionDate": "2021-06-21T09:08:23.283Z",
    "SubscriptionEvent": "created"
}`

![immagine](https://user-images.githubusercontent.com/38665161/122737951-d456bb00-d281-11eb-8cff-227e6b6ed9bb.png)
