### ISSUE TITLE
Search S3 : error on "ProductType" function

### ISSUE THREAD

**Issue by ATroullier** [SercoSPA/CSC-Ground-Segment-Interface-Delivery-Point-Test-Suite#7]
Request :
{{service-root-uri}}/odata/v1/Products?$expand=Attributes&$top=1&$filter=startswith(Name,'S3B_SL_2_LSTCAX')
Function :
test_map.productType=function (element) {
pm.expect(element.Name).eq('productType');pm.expect(element.ValueType).eq('String');pm.expect(element.Value).to.be.a('string');pm.expect(element.Value).to.be.oneOf(["SL_1_RBT___","SL_2_LST___","SL_2_FRP___"]);
};
Display:
{Name: "productType", Value: "SL_2_LSTCAX", ValueType: "String"}
Name: "productType"
Value: "**SL_2_LSTCAX**"
ValueType: "String"
Message :
Test Attribute productType for Product: S3B_SL_2_LSTCAX_20180425T000000_20991231T235959_20180409T120000___________________MPC_O_AL_001.SEN3.zip - 03efc58b-38b1-4354-928e-fbe4d8f7ff84
AssertionError: expected 'SL_2_LSTCAX' to be one of [ Array(3) ]

--> the function is uncompleted.
The full list of product is :
ProductType allowed values :

AX___MF1_AX,AX___MFA_AX,AX___MA1_AX,AX___MF2_AX,AX___MA2_AX,AX___OSF_AX,AX___FPO_AX,AX___FRO_AX,AX___BA__AX,AX___BB2_AX,AX___DEM_AX,AX___LWM_AX,AX___OOM_AX,AX___CLM_AX,AX___TRM_AX,AX___CST_AX,SR___CHDNAX,SR___CHDRAX,SR_1_CONMAX,SR_1_CONCAX,SR_2_CON_AX,SR___LSM_AX,SR_2_IC01AX,SR_2_IC02AX,SR_2_IC03AX,SR_2_IC04AX,SR_2_IC05AX,SR_2_IC06AX,SR_2_IC07AX,SR_2_IC08AX,SR_2_IC09AX,SR_2_IC10AX,SR_2_IC11AX,SR_2_EOT1AX,SR_2_EOT2AX,SR_2_LT1_AX,SR_2_LT2_AX,SR_2_LNEQAX,SR_2_GEO_AX,SR_2_MSS1AX,SR_2_MSS2AX,SR_2_ODLEAX,SR_2_WNDLAX,SR_2_WNDSAX,SR_2_SIGLAX,SR_2_SIGSAX,SR_2_SET_AX,SR_2_SSM_AX,SR_2_MSMGAX,SR_2_CP00AX,SR_2_CP06AX,SR_2_CP12AX,SR_2_CP18AX,SR_2_S1AMAX,SR_2_S2AMAX,SR_2_S1PHAX,SR_2_S2PHAX,SR_2_MDT_AX,SR_2_SHD_AX,SR_2_SSBLAX,SR_2_SSBSAX,SR_2_SD01AX,SR_2_SD02AX,SR_2_SD03AX,SR_2_SD04AX,SR_2_SD05AX,SR_2_SD06AX,SR_2_SD07AX,SR_2_SD08AX,SR_2_SD09AX,SR_2_SD10AX,SR_2_SD11AX,SR_2_SD12AX,SR_2_SI01AX,SR_2_SI02AX,SR_2_SI03AX,SR_2_SI04AX,SR_2_SI05AX,SR_2_SI06AX,SR_2_SI07AX,SR_2_SI08AX,SR_2_SI09AX,SR_2_SI10AX,SR_2_SI11AX,SR_2_SI12AX,SR_2_SST_AX,SR_2_LRC_AX,SR_2_SFL_AX,SR_2_FLT_AX,SR_2_RRC_AX,SR_2_CCT_AX,SR_2_SURFAX,SR_2_RET_AX,SR_2_MLM_AX,SR_2_MAG_AX,SR_2_LUTFAX,SR_2_LUTEAX,SR_2_LUTSAX,SR___ROE_AX,SR_1_CA1LAX,SR_1_CA1SAX,SR_1_CA2KAX,SR_1_CA2CAX,CAL2_C_LTM,MW_1_NIR_AX,MW_1_DNB_AX,MW_1_MON_AX,SL_1_VSC_AX,SR___MGNPAX,SR___POEPAX,SR_2_PMPPAX,SR_2_PCPPAX,SR___MDO_AX,SR___POESAX,SR_2_PMPSAX,SR_2_PCPSAX,SR_2_RMO_AX,SR_2_PMO_AX,SR_2_POL_AX,SR_2_PGI_AX,SR_2_RGI_AX,SR_1_USO_AX,SR___MGNSAX,SR_2_SIC_AX,MW_1_SLC_AX,MW___CHDNAX,MW___CHDRAX,MW___STD_AX,OL_1_EO__AX,OL_1_RAC_AX,OL_1_SPC_AX,OL_1_CLUTAX,OL_1_INS_AX,OL_1_CAL_AX,OL_1_PRG_AX,OL_2_PCP_AX,OL_2_PPP_AX,OL_2_CLP_AX,OL_2_WVP_AX,OL_2_ACP_AX,OL_2_OCP_AX,OL_2_VGP_AX,SL_1_PCP_AX,SL_1_ANC_AX,SL_1_N_S1AX,SL_1_N_S2AX,SL_1_N_S3AX,SL_1_O_S1AX,SL_1_O_S2AX,SL_1_O_S3AX,SL_1_NAS4AX,SL_1_NAS5AX,SL_1_NAS6AX,SL_1_NBS4AX,SL_1_NBS5AX,SL_1_NBS6AX,SL_1_OAS4AX,SL_1_OAS5AX,SL_1_OAS6AX,SL_1_OBS4AX,SL_1_OBS5AX,SL_1_OBS6AX,SL_1_N_S7AX,SL_1_N_S8AX,SL_1_N_S9AX,SL_1_N_F1AX,SL_1_N_F2AX,SL_1_O_S7AX,SL_1_O_S8AX,SL_1_O_S9AX,SL_1_O_F1AX,SL_1_O_F2AX,SL_1_VIC_AX,SL_1_GEO_AX,SL_1_GEC_AX,SL_1_CLO_AX,SL_1_ESSTAX,SL_2_PCP_AX,SL_2_S6N_AX,SL_2_S7N_AX,SL_2_S8N_AX,SL_2_S9N_AX,SL_2_F1N_AX,SL_2_F2N_AX,SL_2_S7O_AX,SL_2_S8O_AX,SL_2_S9O_AX,SL_2_N2_CAX,SL_2_N3RCAX,SL_2_N3_CAX,SL_2_D2_CAX,SL_2_D3_CAX,SL_2_SST_AX,SL_2_SDI3AX,SL_2_SDI2AX,SL_2_SSESAX,**SL_2_LSTCAX**,SL_2_LSTBAX,SL_2_LSTVAX,SL_2_LSTWAX,SL_2_LSTEAX,SL_2_FRPTAX,SL_2_SSTAAX,OL_1_PCPBAX,SL_1_PCPBAX,SL_1_PLTBAX,OL_2_PCPBAX,OL_2_PLTBAX,SL_2_PCPBAX,SL_2_PLTBAX,AX___CHD_AX,GN_1_GSVMAX,GN_1_GSVHAX,GN_1_GCLHAX,GN_1_EOP_AX,GN_1_EOPHAX,GN_1_LSC_AX,GN_1_NAV_AX,GN_1_NSA_AX,GN_1_NTR_AX,GN_1_NPR_AX,GN_1_ATX_AX,GN_1_SAC_AX,GN_1_CHD_AX,GN_1_NSA3AX,GN_1_NTR3AX,GN_1_ATX3AX,GN_1_MANHAX,GN_1_MASSAX,SR_2_NRPPAX,SY_1_TPDBAX,OL_1_MCHDAX,SL_1_MCHDAX,SY_1_PCP_AX,SY_1_CDIBAX,SY_2_PCP_AX,SY_2_PCPSAX,SY_2_RAD_AX,SY_2_RADPAX,SY_2_SPCPAX,SY_2_RADSAX,SY_2_PCPBAX,SY_2_PLTBAX,SY_2_CVPBAX,SY_2_PVPBAX,SY_2_CVSBAX,SY_2_PVSBAX,AX___TAI_AX,SR___MOE_AX,SR___POE_AX,SR___MGN_AX,SR_2_PMP_AX,SR_2_PCP_AX,SR___CHD_AX,SR_1_CON_AX,SR_2_LSM_AX,AX___MAN_AX,AX___MFC_AX,SR___ATB_AX,SR_2_GEOIAX,SR_2_MSS_AX,MW_1_CON_AX,GN___CHD_AX,AX___CN0_AX,AX___GCP_AX,OL_0_AX_PRC,OL_1_CHARAX,OL_1_PROGAX,SL_1_CHF1AX,SL_1_CHF7AX,SL_1_CHS7AX,SL_2_DATBAX,SL_2_FRPAAX,SL_2_SATBAX,SY_1_GCPBAX,SL_2_ACLMAX,SL_2_ART_AX,SL_2_OSR_AX,SL_2_PCPAAX,SY_2_ACLMAX,SY_2_ART_AX,SY_2_LSR_AX,SY_2_OSR_AX,SY_2_PCPAAX,SL_2_CFM_AX,SL_2_FXPAAX,SL_2_PCPFAX,SL_2_PLFMAX,SL_2_SXPAAX,SL_1_IRE_AX,SL_1_LCC_AX,SL_1_CDP_AX,SL_1_CLP_AX,SL_1_ADJ_AX,SL_1_RTT_AX,SY_2_AODCAX

**Comment by ATroullier** [comment]
I understod you wanted to apply a kind of regex with "SL_2_LST___" for all the products "SL_2_LST" but it doesn't work.

**Comment by danPen84** [comment]
Hello,
In the latest Test Suite v1.8 - ICD v1.5 we have more productTypes expected in the lists:
`pm.expect(element.Value).to.be.oneOf(["AX___MF1_AX","AX___MFA_AX","AX___MA1_AX","AX___MF2_AX","AX___MA2_AX","AX___OSF_AX","AX___FPO_AX","AX___FRO_AX","AX___BA__AX","AX___BB2_AX","AX___DEM_AX","AX___LWM_AX","AX___OOM_AX","AX___CLM_AX","AX___TRM_AX","AX___CST_AX","SR___CHDNAX","SR___CHDRAX","SR_1_CONMAX","SR_1_CONCAX","SR_2_CON_AX","SR___LSM_AX","SR_2_IC01AX","SR_2_IC02AX","SR_2_IC03AX","SR_2_IC04AX","SR_2_IC05AX","SR_2_IC06AX","SR_2_IC07AX","SR_2_IC08AX","SR_2_IC09AX","SR_2_IC10AX","SR_2_IC11AX","SR_2_EOT1AX","SR_2_EOT2AX","SR_2_LT1_AX","SR_2_LT2_AX","SR_2_LNEQAX","SR_2_GEO_AX","SR_2_MSS1AX","SR_2_MSS2AX","SR_2_ODLEAX","SR_2_WNDLAX","SR_2_WNDSAX","SR_2_SIGLAX","SR_2_SIGSAX","SR_2_SET_AX","SR_2_SSM_AX","SR_2_MSMGAX","SR_2_CP00AX","SR_2_CP06AX","SR_2_CP12AX","SR_2_CP18AX","SR_2_S1AMAX","SR_2_S2AMAX","SR_2_S1PHAX","SR_2_S2PHAX","SR_2_MDT_AX","SR_2_SHD_AX","SR_2_SSBLAX","SR_2_SSBSAX","SR_2_SD01AX","SR_2_SD02AX","SR_2_SD03AX","SR_2_SD04AX","SR_2_SD05AX","SR_2_SD06AX","SR_2_SD07AX","SR_2_SD08AX","SR_2_SD09AX","SR_2_SD10AX","SR_2_SD11AX","SR_2_SD12AX","SR_2_SI01AX","SR_2_SI02AX","SR_2_SI03AX","SR_2_SI04AX","SR_2_SI05AX","SR_2_SI06AX","SR_2_SI07AX","SR_2_SI08AX","SR_2_SI09AX","SR_2_SI10AX","SR_2_SI11AX","SR_2_SI12AX","SR_2_SST_AX","SR_2_LRC_AX","SR_2_SFL_AX","SR_2_FLT_AX","SR_2_RRC_AX","SR_2_CCT_AX","SR_2_SURFAX","SR_2_RET_AX","SR_2_MLM_AX","SR_2_MAG_AX","SR_2_LUTFAX","SR_2_LUTEAX","SR_2_LUTSAX","SR___ROE_AX","SR_1_CA1LAX","SR_1_CA1SAX","SR_1_CA2KAX","SR_1_CA2CAX","CAL2_C_LTM","MW_1_NIR_AX","MW_1_DNB_AX","MW_1_MON_AX","SL_1_VSC_AX","SR___MGNPAX","SR___POEPAX","SR_2_PMPPAX","SR_2_PCPPAX","SR___MDO_AX","SR___POESAX","SR_2_PMPSAX","SR_2_PCPSAX","SR_2_RMO_AX","SR_2_PMO_AX","SR_2_POL_AX","SR_2_PGI_AX","SR_2_RGI_AX","SR_1_USO_AX","SR___MGNSAX","SR_2_SIC_AX","MW_1_SLC_AX","MW___CHDNAX","MW___CHDRAX","MW___STD_AX","OL_1_EO__AX","OL_1_RAC_AX","OL_1_SPC_AX","OL_1_CLUTAX","OL_1_INS_AX","OL_1_CAL_AX","OL_1_PRG_AX","OL_2_PCP_AX","OL_2_PPP_AX","OL_2_CLP_AX","OL_2_WVP_AX","OL_2_ACP_AX","OL_2_OCP_AX","OL_2_VGP_AX","SL_1_PCP_AX","SL_1_ANC_AX","SL_1_N_S1AX","SL_1_N_S2AX","SL_1_N_S3AX","SL_1_O_S1AX","SL_1_O_S2AX","SL_1_O_S3AX","SL_1_NAS4AX","SL_1_NAS5AX","SL_1_NAS6AX","SL_1_NBS4AX","SL_1_NBS5AX","SL_1_NBS6AX","SL_1_OAS4AX","SL_1_OAS5AX","SL_1_OAS6AX","SL_1_OBS4AX","SL_1_OBS5AX","SL_1_OBS6AX","SL_1_N_S7AX","SL_1_N_S8AX","SL_1_N_S9AX","SL_1_N_F1AX","SL_1_N_F2AX","SL_1_O_S7AX","SL_1_O_S8AX","SL_1_O_S9AX","SL_1_O_F1AX","SL_1_O_F2AX","SL_1_VIC_AX","SL_1_GEO_AX","SL_1_GEC_AX","SL_1_CLO_AX","SL_1_ESSTAX","SL_2_PCP_AX","SL_2_S6N_AX","SL_2_S7N_AX","SL_2_S8N_AX","SL_2_S9N_AX","SL_2_F1N_AX","SL_2_F2N_AX","SL_2_S7O_AX","SL_2_S8O_AX","SL_2_S9O_AX","SL_2_N2_CAX","SL_2_N3RCAX","SL_2_N3_CAX","SL_2_D2_CAX","SL_2_D3_CAX","SL_2_SST_AX","SL_2_SDI3AX","SL_2_SDI2AX","SL_2_SSESAX","SL_2_LSTCAX","SL_2_LSTBAX","SL_2_LSTVAX","SL_2_LSTWAX","SL_2_LSTEAX","SL_2_FRPTAX","SL_2_SSTAAX","OL_1_PCPBAX","SL_1_PCPBAX","SL_1_PLTBAX","OL_2_PCPBAX","OL_2_PLTBAX","SL_2_PCPBAX","SL_2_PLTBAX","AX___CHD_AX","GN_1_GSVMAX","GN_1_GSVHAX","GN_1_GCLHAX","GN_1_EOP_AX","GN_1_EOPHAX","GN_1_LSC_AX","GN_1_NAV_AX","GN_1_NSA_AX","GN_1_NTR_AX","GN_1_NPR_AX","GN_1_ATX_AX","GN_1_SAC_AX","GN_1_CHD_AX","GN_1_NSA3AX","GN_1_NTR3AX","GN_1_ATX3AX","GN_1_MANHAX","GN_1_MASSAX","SR_2_NRPPAX","SY_1_TPDBAX","OL_1_MCHDAX","SL_1_MCHDAX","SY_1_PCP_AX","SY_1_CDIBAX","SY_2_PCP_AX","SY_2_PCPSAX","SY_2_RAD_AX","SY_2_RADPAX","SY_2_SPCPAX","SY_2_RADSAX","SY_2_PCPBAX","SY_2_PLTBAX","SY_2_CVPBAX","SY_2_PVPBAX","SY_2_CVSBAX","SY_2_PVSBAX","AX___TAI_AX","SR___MOE_AX","SR___POE_AX","SR___MGN_AX","SR_2_PMP_AX","SR_2_PCP_AX","SR___CHD_AX","SR_1_CON_AX","SR_2_LSM_AX","AX___MAN_AX","AX___MFC_AX","SR___ATB_AX","SR_2_GEOIAX","SR_2_MSS_AX","MW_1_CON_AX","GN___CHD_AX","AX___CN0_AX","AX___GCP_AX","OL_0_AX_PRC","OL_1_CHARAX","OL_1_PROGAX","SL_1_CHF1AX","SL_1_CHF7AX","SL_1_CHS7AX","SL_2_DATBAX","SL_2_FRPAAX","SL_2_SATBAX","SY_1_GCPBAX","SL_2_ACLMAX","SL_2_ART_AX","SL_2_OSR_AX","SL_2_PCPAAX","SY_2_ACLMAX","SY_2_ART_AX","SY_2_LSR_AX","SY_2_OSR_AX","SY_2_PCPAAX","SL_2_CFM_AX","SL_2_FXPAAX","SL_2_PCPFAX","SL_2_PLFMAX","SL_2_SXPAAX","SL_1_IRE_AX","SL_1_LCC_AX","SL_1_CDP_AX","SL_1_CLP_AX","SL_1_ADJ_AX","SL_1_RTT_AX","SY_2_AODCAX"]);`

**Comment by ATroullier** [comment]
Hello,
Both lists are the same.
It is correct in the test called "Sentinel-3 > LTA > S3_Auxiliary_Data" when the full list is written.
![image](https://user-images.githubusercontent.com/80881293/129909538-39aa39e1-21e7-4856-b39a-ddfb82516731.png)


But in the test "Sentinel-3 > LTA > S3_SLSTR_Products", in 'Tests' tab we can read :
test_map.productType=function (element) {pm.expect(element.Name).eq('productType');pm.expect(element.ValueType).eq('String');pm.expect(element.Value).to.be.a('string');pm.expect(element.Value).to.be.oneOf(["SL_1_RBT___","SL_2_LST___","SL_2_FRP___"]);

If I play the test with parameter 'startswith(Name,'S3B_SL_2_LSTCAX')' it fails.
I suppose you wanted to write a search in all the product 'SL_2_LST' whatever the suffixe, but this syntax doesn't work.

![image](https://user-images.githubusercontent.com/80881293/129909304-23851063-bd8b-4a22-8d52-dc175be6b8e8.png)

**Comment by danPen84** [comment]
In the latest Excel ICD, the Sentinel3 SLSTR Products are not included in the LTA interface.
Moreover, the productType check is fixed in the Test Suite v1.9.1_HF
