### ISSUE TITLE
confusion between Bulk and BatchOder

### ISSUE THREAD

**Issue by ATroullier** [SercoSPA/CSC-Ground-Segment-Interface-Delivery-Point-Test-Suite#8]
**DESCRIPTION**
Make a Bulk
Get an Id in the answer
Make a {{service-root-uri}}/odata/v1/Bulks({{Id}})/BatchOrders

**RESULTS**
Test OData context | AssertionError: expected '$metadata#BatchOrders/$entity' to include 'metadata#Bulks'
FAIL
Test Property StatusMessage for Bulk: 376b1156-bc9e-4528-ab2b-abea18db1882 | AssertionError: expected 'requested products of BatchOrder are available' to be one of [ Array(1) ]
FAIL
Test Property FilterParam for Bulk: 376b1156-bc9e-4528-ab2b-abea18db1882 | AssertionError: expected undefined to be a string
FAIL
Test Property BatchsizeProducts for Bulk: 376b1156-bc9e-4528-ab2b-abea18db1882 | AssertionError: expected undefined to be a number
FAIL
Test Property BatchsizeVolume for Bulk: 376b1156-bc9e-4528-ab2b-abea18db1882 | AssertionError: expected undefined to be a number

**SUGGESTION**
Parameters controls do not match with ICD 1.5.
It seems to be a confusion between tests on "Bulk" and "BatchOrder"

**Comment by danPen84** [comment]
Hello,
Using the latest Test Suite v1.8 with ICD 1.5 we cannot replicate the issue, everything seems correct:

![immagine](https://user-images.githubusercontent.com/38665161/122735249-277b3e80-d27f-11eb-883f-c0fa2be80d24.png)

Please let me know.

**Comment by danPen84** [comment]
Included in the Test Suite since v1.8
